### ISSUE TITLE
Tooling: Create `ok pkg add` command

### ISSUE THREAD

**Issue by staticaland** [oslokommune/ok#158]
## Requirements

- Add specified packages to `packages.yml` file
- Install the added packages
- Automatically choose suitable version constraints if not specified

## Implementation

- Parse command arguments
- Update `packages.yml` file
- Integrate with package installation process

## Decisions

- Follow `poetry add` command structure for familiarity

## Inspiration

- `poetry add` command
- Jakob's Law: Align with user expectations from other CLI tools

Example usage:

```
ok add app app-catapult
```

**Comment by falense** [comment]
Burde denne være `ok pkg add` eller `ok add`?

**Comment by jarlefosen** [comment]
Jeg ser for meg at `ok pkg add` er en fin start, så kan man eventuelt legge til alias for `ok add` dersom man ser at det gir mening i konteksten av alt `ok` eventuelt kommer til å gjøre.

Hvis vi på sikt introduserer `ok x add` og `ok y add` så blir det kanskje forvirrende om `ok add` betyr "add package" eller "add x" eller "add y".

**Comment by yngvark** [comment]
`ok pkg add`. `ok add` bryter med domeneinndelingen vi har gått for, beskrevet [her](https://github.com/oslokommune/golden-path-iac/issues/565#issuecomment-1450035586). Poenget med den er at kommandoer puttes under featuren de hører til.
