### ISSUE TITLE
Installation doc for non Mac users

### ISSUE THREAD

**Issue by poperor** [oslokommune/ok#196]
Right now installation of the ok tool is only documented for Mac users (brew). What about e.g. Linux?  :-)

**Comment by Kielo87** [comment]
Brew works also on Linux https://docs.brew.sh/Homebrew-on-Linux

I'll update the documentation 👍

**Comment by staticaland** [comment]
Manual installation:

```sh
BIN_DIR="$HOME/bin"
PLATFORM=$(uname | tr '[:upper:]' '[:lower:]')
ARCH=$(uname -m)

case $ARCH in
    x86_64)
        ARCH="amd64"
        ;;
    aarch64|arm64)
        ARCH="arm64"
        ;;
    *)
        echo "Unsupported architecture: $ARCH"
        exit 1
        ;;
esac

gh release download \
  --repo "oslokommune/ok" \
  --pattern "ok_*_${PLATFORM}_${ARCH}.tar.gz" \
  --output - | tar -xzOf - ok > "$BIN_DIR/ok"
  
chmod +x "$BIN_DIR/ok"
"$BIN_DIR/ok" version
```

**Comment by poperor** [comment]
There are some potential drawbacks in using Brew on Linux, but if it becomes the standard way of doing things in Golden Path I can live with it. For now I used the manual installation which worked beautifully :-)

**Comment by Kielo87** [comment]
Endringene ligger nå ut https://km.oslo.systems/setup/before-you-start/tools/ok/

**Comment by staticaland** [comment]
We can consider using https://goreleaser.com/customization/nfpm/

> GoReleaser can be wired to [nfpm](https://github.com/goreleaser/nfpm) to generate and publish .deb, .rpm, .apk, .ipk, and Archlinux packages.

**Comment by staticaland** [comment]
https://github.com/wimpysworld/deb-get
